//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSAuditDataField
    {
        public long adf_pk { get; set; }
        public long adf_ada_pk { get; set; }
        public string adf_FieldName { get; set; }
        public int adf_DataType { get; set; }
        public byte[] adf_OldValue { get; set; }
        public byte[] adf_NewValue { get; set; }
    
        public virtual SFSAuditDataAction SFSAuditDataAction { get; set; }
    }
}
