//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkedulexMessage
    {
        public long sm_pk { get; set; }
        public long sm_cust_pk { get; set; }
        public string sm_Subject { get; set; }
        public string sm_Note { get; set; }
        public bool sm_IsActive { get; set; }
        public System.DateTime sm_CreatedorUpdated { get; set; }
        public long sm_Version { get; set; }
        public int sm_CreatedByorUpdatedBy { get; set; }
        public int sm_Remind_us_pk { get; set; }
        public System.DateTime sm_Created { get; set; }
        public int sm_CreatedBy { get; set; }
        public long sm_cl_pk { get; set; }
        public bool sm_IsPriority { get; set; }
        public string sm_Type { get; set; }
        public long sm_Related_pk { get; set; }
        public bool sm_IsRead { get; set; }
    }
}
