//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSRestrictionItem
    {
        public int ri_pk { get; set; }
        public int ri_rs_pk { get; set; }
        public int ri_Action { get; set; }
        public int ri_DaysOfWeek { get; set; }
        public int ri_StartTime { get; set; }
        public int ri_EndTime { get; set; }
        public string ri_Workstation { get; set; }
        public int ri_CreatedBy { get; set; }
        public System.DateTime ri_CreatedAt { get; set; }
        public int ri_Version { get; set; }
    
        public virtual SFSRestriction SFSRestriction { get; set; }
    }
}
