//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardInvoicePayment
    {
        public long StandardInvoicePaymentID { get; set; }
        public string Description { get; set; }
        public long StandardInvoiceID { get; set; }
        public long PaymentTypeID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public bool Void { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual StandardInvoice StandardInvoice { get; set; }
    }
}
