//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IdentityModel.Protocols.WSTrust;
using System.Runtime.ExceptionServices;

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public long PatientID { get; set; }
        [Required]
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        public string HealthCardNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime DateEntered { get; set; }
        public long UserIDEntered { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
