//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardInvoice
    {
        public StandardInvoice()
        {
            this.StandardInvoiceLineItems = new HashSet<StandardInvoiceLineItem>();
            this.StandardInvoicePayments = new HashSet<StandardInvoicePayment>();
        }
    
        public long StandardInvoiceID { get; set; }
        public long CaseID { get; set; }
        public string Description { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal SubTotal { get; set; }
        public decimal GSTHSTVAT { get; set; }
        public decimal PSTOther { get; set; }
        public decimal InterestProposed { get; set; }
        public decimal MOH { get; set; }
        public decimal OtherInsurer { get; set; }
        public decimal Total { get; set; }
        public string AdditionalComments { get; set; }
        public bool SyncToQB { get; set; }
        public bool Void { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ClientCase ClientCase { get; set; }
        public virtual ICollection<StandardInvoiceLineItem> StandardInvoiceLineItems { get; set; }
        public virtual ICollection<StandardInvoicePayment> StandardInvoicePayments { get; set; }
    }
}
