//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCase
    {
        public ClientCase()
        {
            this.CaseActivities = new HashSet<CaseActivity>();
            this.CaseBenefits = new HashSet<CaseBenefit>();
            this.CaseContacts = new HashSet<CaseContact>();
            this.CaseInjuries = new HashSet<CaseInjury>();
            this.CaseManagements = new HashSet<CaseManagement>();
            this.CaseMVAs = new HashSet<CaseMVA>();
            this.CaseNotes = new HashSet<CaseNote>();
            this.CaseProviders = new HashSet<CaseProvider>();
            this.StandardInvoices = new HashSet<StandardInvoice>();
        }
    
        public long CaseID { get; set; }
        public long ClientID { get; set; }
        public long CaseTypeID { get; set; }
        public string Description { get; set; }
        public System.DateTime ReferralDate { get; set; }
        public long CoordinatorUserID { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CaseActivity> CaseActivities { get; set; }
        public virtual ICollection<CaseBenefit> CaseBenefits { get; set; }
        public virtual ICollection<CaseContact> CaseContacts { get; set; }
        public virtual ICollection<CaseInjury> CaseInjuries { get; set; }
        public virtual ICollection<CaseManagement> CaseManagements { get; set; }
        public virtual ICollection<CaseMVA> CaseMVAs { get; set; }
        public virtual ICollection<CaseNote> CaseNotes { get; set; }
        public virtual ICollection<CaseProvider> CaseProviders { get; set; }
        public virtual CaseType CaseType { get; set; }
        public virtual Client Client { get; set; }
        public virtual UserExtendedInformation UserExtendedInformation { get; set; }
        public virtual ICollection<StandardInvoice> StandardInvoices { get; set; }
    }
}
