//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSPermission
    {
        public SFSPermission()
        {
            this.SFSRolesXPermissions = new HashSet<SFSRolesXPermission>();
            this.SFSUsersXPermissions = new HashSet<SFSUsersXPermission>();
        }
    
        public int pm_pk { get; set; }
        public int pm_sproj_pk { get; set; }
        public string pm_Key { get; set; }
        public string pm_Description { get; set; }
        public string pm_Category { get; set; }
        public bool pm_DontAllowReadOnly { get; set; }
        public int pm_BlockedAction { get; set; }
        public string pm_BlockedMsgOrKey { get; set; }
        public bool pm_AlwaysAuditApp { get; set; }
        public bool pm_AlwaysAuditData { get; set; }
        public int pm_Version { get; set; }
        public int pm_CreatedBy { get; set; }
        public System.DateTime pm_CreatedAt { get; set; }
    
        public virtual ICollection<SFSRolesXPermission> SFSRolesXPermissions { get; set; }
        public virtual ICollection<SFSUsersXPermission> SFSUsersXPermissions { get; set; }
    }
}
