//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSUsersXPermission
    {
        public int up_pk { get; set; }
        public int up_us_pk { get; set; }
        public int up_pm_pk { get; set; }
        public int up_Action { get; set; }
        public int up_Restriction { get; set; }
        public bool up_AlwaysAuditApp { get; set; }
        public bool up_AlwaysAuditData { get; set; }
        public int up_CreatedBy { get; set; }
        public System.DateTime up_CreatedAt { get; set; }
    
        public virtual SFSPermission SFSPermission { get; set; }
        public virtual SFSUser SFSUser { get; set; }
    }
}
