//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompany
    {
        public InsuranceCompany()
        {
            this.InsuranceCompanyBranches = new HashSet<InsuranceCompanyBranch>();
        }
    
        public long InsuranceCompanyID { get; set; }
        public string CompanyName { get; set; }
        public string IBCInsurerID { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<InsuranceCompanyBranch> InsuranceCompanyBranches { get; set; }
    }
}
