//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.AppointmentNotes = new HashSet<AppointmentNote>();
        }
    
        public long AppointmentID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public long PatientID { get; set; }
        public long DoctorID { get; set; }
        public long ServiceID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Service Service { get; set; }
        public virtual ICollection<AppointmentNote> AppointmentNotes { get; set; }
    }
}
