//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentNote
    {
        public long AppointmentNotesID { get; set; }
        public string Note { get; set; }
        public long AppointmentID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
