//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prefix
    {
        public Prefix()
        {
            this.CaseContacts = new HashSet<CaseContact>();
            this.Clients = new HashSet<Client>();
            this.ClientContacts = new HashSet<ClientContact>();
        }
    
        public long PrefixID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CaseContact> CaseContacts { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<ClientContact> ClientContacts { get; set; }
    }
}
