//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSAuditEvent
    {
        public long ae_pk { get; set; }
        public int ae_us_pk { get; set; }
        public string ae_EventKey { get; set; }
        public string ae_Description { get; set; }
        public System.DateTime ae_Timestamp { get; set; }
        public byte[] ae_Data { get; set; }
    }
}
