//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSRestriction
    {
        public SFSRestriction()
        {
            this.SFSRestrictionItems = new HashSet<SFSRestrictionItem>();
        }
    
        public int rs_pk { get; set; }
        public int rs_sproj_pk { get; set; }
        public string rs_Name { get; set; }
        public string rs_Description { get; set; }
        public int rs_CreatedBy { get; set; }
        public System.DateTime rs_CreatedAt { get; set; }
        public int rs_Version { get; set; }
    
        public virtual ICollection<SFSRestrictionItem> SFSRestrictionItems { get; set; }
    }
}
