//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardInvoiceLineItem
    {
        public long StandardInvoiceLineItemID { get; set; }
        public long GoodAndServiceID { get; set; }
        public long AppointmentResourceID { get; set; }
        public string Attribute { get; set; }
        public decimal Quantity { get; set; }
        public string MeasureID { get; set; }
        public System.DateTime DateOfService { get; set; }
        public bool GSTHSTVAT { get; set; }
        public bool PSTOther { get; set; }
        public decimal LineCost { get; set; }
        public bool Void { get; set; }
        public long StandardInvoiceID { get; set; }
        public long CaseManagementID { get; set; }
        public long ActivityBookingID { get; set; }
    
        public virtual StandardInvoice StandardInvoice { get; set; }
    }
}
