//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSAuditDataAction
    {
        public SFSAuditDataAction()
        {
            this.SFSAuditDataFields = new HashSet<SFSAuditDataField>();
        }
    
        public long ada_pk { get; set; }
        public int ada_us_pk { get; set; }
        public string ada_TableName { get; set; }
        public byte ada_Action { get; set; }
        public System.DateTime ada_Timestamp { get; set; }
    
        public virtual ICollection<SFSAuditDataField> SFSAuditDataFields { get; set; }
    }
}
