//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public ActivityType()
        {
            this.CaseActivities = new HashSet<CaseActivity>();
        }
    
        public long ActivityTypeID { get; set; }
        public long ActivitySubTypeID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public long GoodAndServiceID { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ActivitySubType ActivitySubType { get; set; }
        public virtual ICollection<CaseActivity> CaseActivities { get; set; }
    }
}
