//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentResource
    {
        public AppointmentResource()
        {
            this.ActivityBookings = new HashSet<ActivityBooking>();
            this.AppointmentResourceAvailableTimes = new HashSet<AppointmentResourceAvailableTime>();
            this.AppointmentResourceDayOffs = new HashSet<AppointmentResourceDayOff>();
            this.CaseManagements = new HashSet<CaseManagement>();
            this.CaseProviders = new HashSet<CaseProvider>();
        }
    
        public long AppointmentResourceID { get; set; }
        public long AppointmentResourceBookingTypeID { get; set; }
        public Nullable<long> CompanyBranchID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
        public string HCAIProviderRegistryID { get; set; }
        public string CollegeRegistrationNumber { get; set; }
        public string WebAccessCode { get; set; }
        public bool DoubleBookingAllowed { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public long ProvinceOrStateID { get; set; }
        public string PostalCodeOrZipCode { get; set; }
        public long CountryID { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExtension { get; set; }
        public string WorkFax { get; set; }
        public string OtherPhone { get; set; }
        public string WorkEmail { get; set; }
        public string AdditionalEmail { get; set; }
        public string Credentials { get; set; }
        public string Comments { get; set; }
        public string ResumeName { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ActivityBooking> ActivityBookings { get; set; }
        public virtual AppointmentResourceBookingType AppointmentResourceBookingType { get; set; }
        public virtual Country Country { get; set; }
        public virtual ProvinceOrState ProvinceOrState { get; set; }
        public virtual ICollection<AppointmentResourceAvailableTime> AppointmentResourceAvailableTimes { get; set; }
        public virtual ICollection<AppointmentResourceDayOff> AppointmentResourceDayOffs { get; set; }
        public virtual ICollection<CaseManagement> CaseManagements { get; set; }
        public virtual ICollection<CaseProvider> CaseProviders { get; set; }
    }
}
