//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseManagement
    {
        public long CaseManagementID { get; set; }
        public long CaseID { get; set; }
        public Nullable<long> DocumentTypeID { get; set; }
        public string FileName { get; set; }
        public string NewFileName { get; set; }
        public Nullable<long> CaseActivityID { get; set; }
        public string HCAIStatus { get; set; }
        public System.DateTime DateOfService { get; set; }
        public long GoodAndServiceID { get; set; }
        public string GoodAndServiceAtt { get; set; }
        public string GoodAndServiceDesc { get; set; }
        public long AppointmentResourceID { get; set; }
        public decimal Quantity { get; set; }
        public long MeasureID { get; set; }
        public bool GSTHSTVAT { get; set; }
        public decimal LineCost { get; set; }
        public bool Billed { get; set; }
        public bool PSTOther { get; set; }
        public string PlanNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal BilledAmount { get; set; }
        public decimal ApprovedAmount { get; set; }
        public bool Visible { get; set; }
        public decimal WIPAmount { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual AppointmentResource AppointmentResource { get; set; }
        public virtual CaseActivity CaseActivity { get; set; }
        public virtual ClientCase ClientCase { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual GoodAndService GoodAndService { get; set; }
        public virtual Measure Measure { get; set; }
    }
}
