//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseInjury
    {
        public long CaseInjuryID { get; set; }
        public long CaseID { get; set; }
        public long InjuryCodeID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ClientCase ClientCase { get; set; }
        public virtual InjuryCode InjuryCode { get; set; }
    }
}
