//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseActivity
    {
        public CaseActivity()
        {
            this.ActivityBookings = new HashSet<ActivityBooking>();
            this.CaseManagements = new HashSet<CaseManagement>();
        }
    
        public long CaseActivityID { get; set; }
        public long ActivityTypeID { get; set; }
        public long CaseID { get; set; }
        public string Description { get; set; }
        public bool Completed { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ActivityBooking> ActivityBookings { get; set; }
        public virtual ActivityType ActivityType { get; set; }
        public virtual ClientCase ClientCase { get; set; }
        public virtual ICollection<CaseManagement> CaseManagements { get; set; }
    }
}
