//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseType
    {
        public CaseType()
        {
            this.ClientCases = new HashSet<ClientCase>();
            this.DocumentTypes = new HashSet<DocumentType>();
        }
    
        public long CaseTypeID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ClientCase> ClientCases { get; set; }
        public virtual ICollection<DocumentType> DocumentTypes { get; set; }
    }
}
