//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseMVA
    {
        public long CaseMVAID { get; set; }
        public long CaseID { get; set; }
        public System.DateTime DateofAccident { get; set; }
        public string ClaimNumber { get; set; }
        public string PolicyNumber { get; set; }
        public long AdjusterID { get; set; }
        public bool CAT { get; set; }
        public bool TransportationRequired { get; set; }
        public bool InterpreterRequired { get; set; }
        public long LanguageID { get; set; }
        public bool PolicyHolderSameAsApplicant { get; set; }
        public string PolicyHolderFirstName { get; set; }
        public string PolicyHolderLastName { get; set; }
        public bool IsThereOtherInsuranceCoverage { get; set; }
        public bool Closed { get; set; }
        public System.DateTime ClosedDate { get; set; }
        public string OtherInsurer1Name { get; set; }
        public string OtherInsurer1Plan { get; set; }
        public string OtherInsurer1PolicyNumber { get; set; }
        public string OtherInsurer1NameofThePlanMember { get; set; }
        public string OtherInsurer1Identifier { get; set; }
        public string OtherInsurer2Name { get; set; }
        public string OtherInsurer2Plan { get; set; }
        public string OtherInsurer2PolicyNumber { get; set; }
        public string OtherInsurer2NameofThePlanMember { get; set; }
        public string OtherInsurer2Identifier { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual Adjuster Adjuster { get; set; }
        public virtual ClientCase ClientCase { get; set; }
        public virtual Language Language { get; set; }
    }
}
