//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ClientCases = new HashSet<ClientCase>();
            this.ClientContacts = new HashSet<ClientContact>();
        }
    
        public long ClientID { get; set; }
        public long PrefixID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public long GenderID { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public long ProvinceOrStateID { get; set; }
        public string PostalCodeOrZipCode { get; set; }
        public long CountryID { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string PersanalFax { get; set; }
        public string PersonalEmail { get; set; }
        public long MaritalStatusID { get; set; }
        public string SocialInsuranceNumber { get; set; }
        public string HealthCardNumber { get; set; }
        public string DriversLicenseNumber { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Height { get; set; }
        public string Occupation { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExtension { get; set; }
        public string WorkFax { get; set; }
        public string WorkEmail { get; set; }
        public byte[] Picture { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ClientCase> ClientCases { get; set; }
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MaritalState MaritalState { get; set; }
        public virtual Prefix Prefix { get; set; }
        public virtual ProvinceOrState ProvinceOrState { get; set; }
        public virtual ICollection<ClientContact> ClientContacts { get; set; }
    }
}
