//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBranch
    {
        public long CompanyBranchID { get; set; }
        public long CompanyID { get; set; }
        public string TrandeName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public long ProvinceOrStateID { get; set; }
        public string PostalCodeOrZipCode { get; set; }
        public long CountryID { get; set; }
        public string Phone { get; set; }
        public string PhoneExtension { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string HCAIFacilityRegistryID { get; set; }
        public string TaxRegistrationNumber { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual ProvinceOrState ProvinceOrState { get; set; }
    }
}
