//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayofWeek
    {
        public DayofWeek()
        {
            this.AppointmentResourceAvailableTimes = new HashSet<AppointmentResourceAvailableTime>();
        }
    
        public long DayofWeekID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<AppointmentResourceAvailableTime> AppointmentResourceAvailableTimes { get; set; }
    }
}
