//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public DocumentType()
        {
            this.CaseManagements = new HashSet<CaseManagement>();
        }
    
        public long DocumentTypeID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
        public long CaseTypeID { get; set; }
        public bool Editable { get; set; }
        public bool Uploadable { get; set; }
    
        public virtual ICollection<CaseManagement> CaseManagements { get; set; }
        public virtual CaseType CaseType { get; set; }
    }
}
