//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompanyBranch
    {
        public InsuranceCompanyBranch()
        {
            this.Adjusters = new HashSet<Adjuster>();
        }
    
        public long InsuranceCompanyBranchID { get; set; }
        public long InsuranceCompanyID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
        public string IBCBranchID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public long ProvinceOrStateID { get; set; }
        public string PostalCodeOrZipCode { get; set; }
        public long CountryID { get; set; }
        public string Phone { get; set; }
        public string PhoneExtension { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Adjuster> Adjusters { get; set; }
        public virtual InsuranceCompany InsuranceCompany { get; set; }
    }
}
