//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSProject
    {
        public int sproj_pk { get; set; }
        public string sproj_Name { get; set; }
        public string sproj_Description { get; set; }
        public string sproj_SecurityKey { get; set; }
        public System.DateTime sproj_CreatedAt { get; set; }
        public int sproj_Version { get; set; }
    }
}
