//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSRole
    {
        public SFSRole()
        {
            this.SFSRolesXPermissions = new HashSet<SFSRolesXPermission>();
            this.SFSUsersXRoles = new HashSet<SFSUsersXRole>();
        }
    
        public int rl_pk { get; set; }
        public int rl_sproj_pk { get; set; }
        public string rl_Role { get; set; }
        public string rl_Description { get; set; }
        public int rl_Version { get; set; }
        public bool rl_AlwaysAuditApp { get; set; }
        public bool rl_AlwaysAuditData { get; set; }
        public int rl_CreatedBy { get; set; }
        public System.DateTime rl_CreatedAt { get; set; }
    
        public virtual ICollection<SFSRolesXPermission> SFSRolesXPermissions { get; set; }
        public virtual ICollection<SFSUsersXRole> SFSUsersXRoles { get; set; }
    }
}
