//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFSRolesXPermission
    {
        public int rp_pk { get; set; }
        public int rp_rl_pk { get; set; }
        public int rp_pm_pk { get; set; }
        public int rp_Action { get; set; }
        public int rp_Restriction { get; set; }
        public bool rp_AlwaysAuditApp { get; set; }
        public bool rp_AlwaysAuditData { get; set; }
        public System.DateTime rp_CreatedAt { get; set; }
        public int rp_CreatedBy { get; set; }
    
        public virtual SFSPermission SFSPermission { get; set; }
        public virtual SFSRole SFSRole { get; set; }
    }
}
