//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjuster
    {
        public Adjuster()
        {
            this.CaseMVAs = new HashSet<CaseMVA>();
        }
    
        public long AdjusterID { get; set; }
        public long InsuranceCompanyBranchID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string PhoneExtension { get; set; }
        public string CellPhone { get; set; }
        public string OtherPhone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Code { get; set; }
        public string By { get; set; }
        public System.DateTime CreatedOrUpdated { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
    
        public virtual InsuranceCompanyBranch InsuranceCompanyBranch { get; set; }
        public virtual ICollection<CaseMVA> CaseMVAs { get; set; }
    }
}
